version: '3'

services:

  news-getter-server:
    container_name: news-getter-server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - service-db
    ports:
      - 8082:8082
#    networks:
#      - spring-cloud-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update


  service-db:
    image: 'postgres:13-alpine'
    container_name: service-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#networks:
#  spring-cloud-network:
#    driver: bridge