-- INSERT INTO app_user (user_name, password, active, roles)
-- VALUES ('Patient0', '$2a$10$c6uBZIxGObcIE.YJcVflSOBUOMBlx3c.AFF6avkrb8JsJgY9e/tJy', true, 'ROLE_USER');
-- Change this, this is just an example